//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _29368081_FIT5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string booking_name { get; set; }
        public System.DateTime datetime { get; set; }
        public int booking_periodLength { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
